### ISSUE TITLE
link doxygen on github front page

### ISSUE THREAD

**Issue by jeffhammond** [solomonik/ctf#1]
I recommend setting http://ctf.eecs.berkeley.edu as the home page so people that come to this page first know where the docs are.

If it's in the README, one has to scroll down to see that...

**Comment by solomonik** [comment]
I don't see how to change the github homepage or how to properly embed html in the README.  There as a gh-pages (Github pages) option, but it does not seem to be nicely connected to the github repo at this point.  For now, I shortened the README, so the docs link should be clear.  Let me know if you have further more specific suggestions on doc presentation improvement.

**Comment by solomonik** [comment]
Done.
