### ISSUE TITLE
MPI_DOUBLE_COMPLEX is an "invalid datatype"

### ISSUE THREAD

**Issue by devinamatthews** [solomonik/ctf#10]
OpenMPI 1.10 on OSX gives the following error when using the `MPI_DOUBLE_COMPLEX` datatype (from C++):

> [Devins-iMac:62206] *** An error occurred in MPI_Alltoallv
> [Devins-iMac:62206] *** reported by process [1094451201,0]
> [Devins-iMac:62206] *** on communicator MPI_COMM_WORLD
> [Devins-iMac:62206] *** MPI_ERR_TYPE: invalid datatype
> [Devins-iMac:62206] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
> [Devins-iMac:62206] ***    and potentially your MPI job)

A simple program to test this is:

```C
#include "mpi.h"

int main(int argc, char **argv)
{
    char a[16], b[16];
    int n = 1, d = 0;
    MPI_Init(&argc, &argv);
    MPI_Alltoallv(&a, &n, &d, MPI_DOUBLE_COMPLEX,
                  &b, &n, &d, MPI_DOUBLE_COMPLEX, MPI_COMM_WORLD);
    MPI_Finalize();
    return 0;
}
```

In the context of `CTF_int::CommData::all_to_allv` it might be better to just use `MPI_BYTE` and scale the counts/displs accordingly.

**Comment by devinamatthews** [comment]
I should note that I have no idea why CTF is trying to communicate a 16-byte datatype when I am only using double.

**Comment by solomonik** [comment]
The problem with always using byte-sized counts is reaching 32-bit overflows faster.  MPI_DOUBLE_COMPLEX was being used as the generic 16-byte datatype to communicate key-value pairs.  I switched that to MPI_LONG_DOUBLE.  However, MPI_COMPLEX and DOUBLE_COMPLEX types are still being used for truly complex types.  I switched these to MPI_C_COMPLEX (https://computing.llnl.gov/tutorials/mpi/#Derived_Data_Types), presumably this is what OpenMPI needs, while MPICH works with the former.  Please check that the make test2 and make test4 work for you (if you see the 3D DFT error, please check with -O0).  Thanks.

**Comment by devinamatthews** [comment]
Yes, looks like MPI_COMPLEX -> MPI_C_COMPLEX and MPI_DOUBLE_COMPLEX -> 
MPI_C_DOUBLE_COMPLEX is what you want. I would avoid MPI_LONG_DOUBLE 
since I think it is optional and could in theory be defined as 12 bytes 
or 12 bytes of data in a 16 byte extent.

As for 32-bit overflows, could you not simply call MPI_Alltoallv 
multiple times? For messages that large the additional latency should be 
negligible. Will check tests and report back.

**Comment by jeffhammond** [comment]
1) `MPI_LONG_DOUBLE` is horrible, because C's `long double` is horrible.  Do not use either of them.  `long double` is not guaranteed to be a 16B type.  See [Wikipedia](https://en.wikipedia.org/wiki/Long_double) for details.

2) `MPI_COMPLEX` and `MPI_DOUBLE_COMPLEX` are _Fortran_ types.  If you want to pass `std::complex<float>` and `std::complex<double>`, you must use `MPI_CXX_FLOAT_COMPLEX￼` and `MPI_CXX_DOUBLE_COMPLEX`, respectively.  See page 674 of the MPI 3.1 standard.

3) If you want to overcome large-count issues, use the approach [BigMPI](https://github.com/jeffhammond/BigMPI) does or break up your messages into chunks.  You will find that MPI implementations will break if you pass more than 2Gi bytes to them, regardless of the `count` argument, because most MPI functions will convert to bytes internally.   See [this ticket](https://trac.mpich.org/projects/mpich/ticket/2311) as an example.

**Comment by solomonik** [comment]
My alltoallv wrapper function already has handing for overflow where it uses a isend/irecv implementation.  However, I'd prefer the code uses MPI_Alltoallv rather than that as often as possible for better potential performance.

If MPI_LONG_DOUBLE is bad should I use MPI_C_DOUBLE_COMPLEX or MPI_CXX_DOUBLE_COMPLEX?

**Comment by solomonik** [comment]
Checked the standard doc, I see indeed _CXX_ and not _C_, will commit that shortly.

**Comment by devinamatthews** [comment]
Yeah I guess technically you should use MPI_CXX_[DOUBLE_]COMPLEX. For 
the alltoallv problem, you could do several things:

1) Split into N calls where count[i] is 1/N of the original value for 
each call (and adjust displs accordingly), such that each call is safe.

2) Communicate count[0]...count[k] such that the call is safe, then 
count[k+1]...count[l] etc.

3) A hierarchical decomposition (which could still use alltoallv).

4) Any other method which satisfies latency, load balancing, etc. 
acceptably.

**Comment by jeffhammond** [comment]
# Type issues

C `long double` does not have a fixed width, nor is it guaranteed to correspond to an IEEE type.  C `_Complex` floats have a fixed-width.

Whether or not you use complex depends on your faith in MPI implementers.  @poulson has seen enough issues with MPI complex support that he has workarounds in Elemental for this case.

# Count issues

Unfortunately, `MPI_Alltoallv` has not only a count overflow problem, but an displacement overflow problem, so writing a pipelined version using it will still break when you try to set the `int` displacements.

The BigMPI paper has a list of workarounds, or you can try to use the method described in https://github.com/jeffhammond/BigMPI/issues/25, which is not implemented in BigMPI yet.

Torsten had the foresight to fix the displacement overflow problem in the neighborhood collective interface, but that requires MPI-3, and you have to create a distributed graph communicator to use those.

I don't think it is that hard to schedule send-recv such that using this as the workaround for count-overflow issues is unreasonable.

**Comment by devinamatthews** [comment]
> Unfortunately, |MPI_Alltoallv| has not only a count overflow problem, 
but an displacement overflow problem, so writing a pipelined
 > version using it will still break when you try to set the |int| 
displacements.

In the version which only communicates some processes' data, can one not 
adjust the base pointer as well to make it fit in 32-bit?

**Comment by jeffhammond** [comment]
@devinamatthews Back to the original issue, it is a bug in Open-MPI that you cannot use `MPI_DOUBLE_COMPLEX` from C/C++.  MPI is designed to allow interlanguage communication...

**Comment by solomonik** [comment]
Ok, I pushed in changes, switching to MPI_CXX_DOUBLE_COMPLEX.  I am going to continue using that as a generic type for 16-byte alltoallv until there issues are observed.

I think the isend/irecv overflow solution I have in the alltoallv wrapper is the right one.

**Comment by devinamatthews** [comment]
Do you know why CTF would be attempting to use a 16 byte type for doubles?

**Comment by solomonik** [comment]
As I mentioned above to communicate key value pairs (int64_t, double).  Thanks for the bug reports.

**Comment by jeffhammond** [comment]
@devinamatthews The case where one has counts that overflow but displacements do not is unlikely.  Unless the only count that overflows is the last one in the count vector, the displacements will overflow.

@solomonik I agree.  It is by far the most reliable option, as lack of MPI-3 and internal overflow issues in nearly all MPI implementations will break the "better" methods.

FWIW There's a good change we will fix all of this in MPI-4 :rage1:

**Comment by devinamatthews** [comment]
Ah, that makes sense now. Is it not necessary to consider 24-byte and 
larger cases then (double complex, long double etc.)?

**Comment by solomonik** [comment]
For those I am using the Isend/Irecv solution in alltoallv (what most MPI implementations do is unlikely to be smarter), and elsewhere I create custom MPI datatypes.

**Comment by jeffhammond** [comment]
@devinamatthews While `long double` is horrible, the MPI implementation will support the MPI C/C++ datatype equivalents according to the compiler it was built with.  This is an exception to the ABI compatibility of MPI as a C library, because bad things will happen if `sizeof(long double)` is not the same in the compiler used to build MPI and the compiler used to build your application.

**Comment by solomonik** [comment]
Actually I am not sure why I did not use custom datatypes + MPI_Alltoallv when the datum size is not 4/8/16, but whatever, maybe will adjust this in the near future.

**Comment by devinamatthews** [comment]
Apparently MPI_CXX_[LONG_]DOUBLE_COMPLEX and MPI_CXX_BOOL are not defined by OpenMPI 1.6.5. The C versions (MPI_C_DOUBLE_COMPLEX and MPI_C_BOOL) do work. Also, there are still some instances of MPI_COMPLEX which should be changed to MPI_C_COMPLEX/MPI_CXX_COMPLEX.

I think the C complex versions should work fine as both standards specify no padding and have the same float/double width. Both C99 and C++ bool are *usually* 1 byte, although they can be larger (and even if so would almost certainly be the same size). Some configure magic can work around this if it becomes a problem.

**Comment by devinamatthews** [comment]
Or you could cast bools to int/char whatever.

**Comment by jeffhammond** [comment]
@devinamatthews Are you testing the preprocessor symbol `MPI_VERSION` prior to using MPI-3 features?  I doubt Open-MPI 1.6.5 supports MPI-3.

Those datatypes were added in MPI-3 because we deleted the C++ bindings (omitting them was always an oversight, but it wasn't noticed until we started thinking about how C++ programs would use the C bindings).

Upgrading to a newer release of Open-MPI is not hard, but you would be better off using MPICH 3.2.  MPICH has supported MPI-3 for years.

**Comment by devinamatthews** [comment]
Well, I'm not admin on this system, but yeah upgrading is the 
workaround. Maybe we need to set a supported minimum version (like I 
suggested for gcc/icpc/clang)?

**Comment by devinamatthews** [comment]
Opening a new issue re required MPI3 support.

**Comment by jeffhammond** [comment]
@devinamatthews MPI is a completely userspace install.

**Comment by devinamatthews** [comment]
True, but annoying to do.

**Comment by devinamatthews** [comment]
Also, I'd probably have to static link to get it to work right on the 
compute nodes.

**Comment by jeffhammond** [comment]
@devinamatthews If your home directory is mounted on the compute nodes, you will be fine.  Just build MPICH with the rpath option enabled.

Building MPICH from source is trivial compared to everything else you do.  Grab https://github.com/ParRes/Kernels/blob/master/travis/install-mpi.sh and invoke `./install-mpi.sh $HOME/mpich mpich`.

I guess if you have InfiniBand, you need to build MVAPICH2 instead of MPICH, but everything else is the same.

**Comment by solomonik** [comment]
Sounds like we can get OpenMPI working by switching from MPI_CXX_... to MPI_C_..., did I understand this correctly.  Jeff doesn't MPICH also recognize MPI_C_... without issue?  Did you only recommend MPI_CXX because of the standard?

**Comment by devinamatthews** [comment]
Yes, C instead of CXX works for me. I believe standards compliance is 
the main issue, depends how much you care about strict compliance.

**Comment by solomonik** [comment]
I'd vote for doing what works instead of what is supposed to work but
doesn't.

**Comment by devinamatthews** [comment]
Works for me. Also note that there are still some MPI_COMPLEX remaining, 
could crop back up when using complex<float>.

**Comment by solomonik** [comment]
I pushed a change from _CXX_ to _C_ and changed one MPI_COMPLEX that I had missed last time.  Please let me know if there are other issues with OpenMPI.

**Comment by jeffhammond** [comment]
`MPI_C_DOUBLE_COMPLEX` corresponds to C99's `_Complex double`, not C++'s `std::complex<double>`.  I recall that these types are not guarantee to interoperate, and can find no evidence on Wikipedia, StackOverflow, N3936 (C++14 draft) or N1570 (C11 draft) to contradict my recollection.

As long as `sizeof()` returns the same thing for both, every function that does not involve `MPI_Op` will be fine, but the moment you call a reduction, you rely upon compiler-specific behavior.

**Comment by jeffhammond** [comment]
The commit to test for `MPI_CXX_*` types was in November 2012 (https://github.com/jeffhammond/mpich/commit/7a92737db6ccc72a04d5737a83c78409c5d4b9b0), so I have to assume these features have been supported for a long time.

**Comment by solomonik** [comment]
Getting CTF to work with OpenMPI seems to me like a more concrete concern than the complex type interoperability.  I have trouble believing compilers do something clever for a complex type or operations on it that would affect MPI, its just two doubles (even Gauss's trick shouldn't change anything as far as I see).  There are std::complex tests in the test_suite that also ought to catch any such issue if it were to arise.

**Comment by jeffhammond** [comment]
`MPI_CXX_DOUBLE_COMPLEX` and friends were an [MPI 2.2 errata](http://www.mpi-forum.org/docs/mpi-2.2/errata-22.pdf).  There is no excuse for any recent version of Open-MPI to not support them.  This is an Open-MPI bug and @devinamatthews should use an implementation based on MPICH or use a more recent version of Open-MPI.  The latest version (i.e. git HEAD) supports them.

**Comment by solomonik** [comment]
Possibly a newer MPI version would also address the other bug Devin
reported with write(). I don't believe there is CTF bug that would cause an
error for that test. But if sent data with complex datatype was corrupted
that assert could trigger.

**Comment by jeffhammond** [comment]
POSIX `write`?  How many bytes?  From what @roblatham00 has taught me in the context of BigMPI, one must check the return value from such functions as soon as they get into the gigabyte range.

**Comment by solomonik** [comment]
No, no a CTF Tensor::write()
