### ISSUE TITLE
Assertion failure in readwrite

### ISSUE THREAD

**Issue by devinamatthews** [solomonik/ctf#13]
Attached program hits an assertion:

src/redistribution/sparse_rw.cxx:708 via
src/redistribution/sparse_rw.cxx:985 via
src/tensor/untyped_tensor.cxx:1052

Assertion fails on 48 cores, works on 1 core.

[test.tar.gz](https://github.com/solomonik/ctf/files/83209/test.tar.gz)

**Comment by solomonik** [comment]
Really?  Doesn't this test just fill a nonsymmetric matrix with zeros?  I get no error when running it with 48 MPI processors.

**Comment by devinamatthews** [comment]
Hmm, fails for me. Let me try a clean pull.

**Comment by solomonik** [comment]
If it still fails let me know what compiler and flags you are you using.
Also, that ASSERT is a macro that I thought should not even trigger on a
build without -DDEBUG or -DVERBOSE.

**Comment by devinamatthews** [comment]
This is compiled with "-g -O0 -DDEBUG=1".

**Comment by devinamatthews** [comment]
Yes, this still happens after a clean pull (from master). My compile line is:

```
mpicxx -o test.x -std=c++11 -fopenmp -g -O0 -DDEBUG=1 -I/home1/dmatthews/src/aquarius/src/external/ctf/include -L/home1/dmatthews/src/aquarius/src/external/ctf/lib test.cxx -lctf -L/apps1/intel/13.1/lib/intel64 -Wl,--start-group /apps1/intel/13.1/mkl/lib/intel64/libmkl_intel_lp64.a /apps1/intel/13.1/mkl/lib/intel64/libmkl_core.a /apps1/intel/13.1/mkl/lib/intel64/libmkl_gnu_thread.a -Wl,--end-group -lpthread -lm
```

OpenMPI 1.6.5
GCC 4.8.2

Also, this is using flat MPI on 6 nodes with 8 cores each if that matters. config.mk is:

```bash
### LINK TIME LIBRARIES AND FLAGS
#libraries and flags for link time (irrelevant if only building CTF lib and not examples/tests)
BLAS_LIBS   =  
LDFLAGS     = 

### COMPILE TIME INCLUDES AND FLAGS
#C++ compiler 
CXX         = mpicxx -std=c++0x
#includes for compile time
INCLUDES    = 
#optimization flags, some intel compiler versions may run into errors when using -fast or -ipo
CXXFLAGS    = -O0 -g -fopenmp -Wall 
#command to make library out of object files
AR          = ar

#macros to be defined throughout the code
DEFS        = -D_POSIX_C_SOURCE=200112L -D__STDC_LIMIT_MACROS -DFTN_UNDERSCORE=1 

### Optional: PROFILING AND TUNING
#uncomment below to enable performance profiling
#DEFS       += -DPROFILE -DPMPI
#uncomment below to enable automatic performance tuning (loses reproducibility of results)
#Note: -DTUNE requires lapack (include -mkl or -llapack in BLAS_LIBS)
#DEFS       += -DTUNE

### Optional: DEBUGGING AND VERBOSITY
#uncomment below to enable CTF execution output (1 for basic contraction information on start-up and contractions)
#DEFS       += -DVERBOSE=1
#uncomment to set debug level to dump information about mapping and internal CTF actions and activate asserts
DEFS       += -DDEBUG=1

### FULL COMPILE COMMAND AND LIBRARIES
#used to compile all plain C++ files
FCXX        = $(CXX) $(CXXFLAGS) $(DEFS) $(INCLUDES)
#link-line for all executables
LIBS        = $(BLAS_LIBS) $(LDFLAGS)
#compiler for CUDA files (used to compile CUDA code only when -DOFFLOAD and -DUSE_CUDA are in DEFS, otherwise should be same as FCXX with -x c++)
OFFLOAD_CXX = $(CXX) -x c++ $(CXXFLAGS) $(DEFS) $(INCLUDES)
```

**Comment by solomonik** [comment]
Very strange.  Does the CTF test_suite work on 48 cores with this build
setup?

**Comment by devinamatthews** [comment]
Something is very messed up. The testsuite runs fine on one core, but on 
48 I eventually wind up with an invalid datatype error on MPI_DOUBLE 
(during a redistribution on a complex<double> tensor...).

I suppose I'll try MPICH.

**Comment by devinamatthews** [comment]
This + the test suite runs OK on Stampede (48 cores). I'll try MPICH on the other system and if that works I'll close the issue.

**Comment by devinamatthews** [comment]
Test suite passes with MPICH. OpenMPI is some seriously messed up shit.

**Comment by solomonik** [comment]
Well *old* OpenMPI implementations are notoriously buggy.  I will switch
CTF back to using _CXX_ instead of _C_ for datatypes then.
