### ISSUE TITLE
NERSC Cori is undetected by configure script

### ISSUE THREAD

**Issue by epifanovsky** [solomonik/ctf#16]
Attempting to configure CTF on cori.nersc.gov returns:
```
> ./configure
Checking hostname... Hostname not recognized, assuming generic Linux host.
Checking compiler type/version... ./configure: line 233: mpicxx: command not found
./configure: line 234: mpicxx: command not found
Could not determine underlying C/C++ compilers.
```

Hacking configure to replace "edison" with "cori" seems to work.

**Comment by jeffhammond** [comment]
We candidate better and detect Cray XC generally from file path or other
triggers.

On Friday, March 4, 2016, Evgeny Epifanovsky <notifications@github.com>
wrote:

> Attempting to configure CTF on cori.nersc.gov returns:
>
> > ./configure
> Checking hostname... Hostname not recognized, assuming generic Linux host.
> Checking compiler type/version... ./configure: line 233: mpicxx: command not found
> ./configure: line 234: mpicxx: command not found
> Could not determine underlying C/C++ compilers.
>
> Hacking configure to replace "edison" with "cori" seems to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/solomonik/ctf/issues/16>.
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by solomonik** [comment]
Added cori to be recognized as edison is.  May introduce a more robust system for toolchain specification in the future, but do not see it as high priority for now.
