### ISSUE TITLE
segmentation fault in contraction with many indices

### ISSUE THREAD

**Issue by kostrzewa** [solomonik/ctf#18]
As a test for writing more understandable code for so-called quark line contractions for the construction of observables in lattice QCD, I have attempted to use Cyclops.

In the following code I unfortunately encounter a segmentation fault, however:
https://github.com/kostrzewa/nyom/blob/master/benchmarks/bench_ctf/bench_ctf.cpp

It's contraction of two six-index objects (indices run over different ranges) with a number of two-index objects, resulting in a two-index object (a 3x3 complex matrix).

If you have some time, I would really appreciate if you could see if I'm doing something wrong which might cause the segfault. The code should compile straightforwardly with the included Makefile.

**Comment by solomonik** [comment]
Hi, that seems like a very interesting application.

I reproduced a segmentation fault when running your code.  However, it happened earlier, the symmetries for the matrices were specified incorrectly.  Also, one of the loops that defines the initial tensor data is wrong.  After fixing these, the code executed, but CTF computed extremely high order intermediates to evaluate the expression (like order 14, all sums were being done at the end).  CTF is currently not smart at picking the right `factorizaton' (order of contraction evaluations), when doing A*B*C*D*...  (Factorization is a hard problem in general, some solutions exist, like TCE).  Applications are currently expected to do this manually, e.g. AB =A*B; ABC = AB*C; etc.  I made a pull request to your code, correcting the bugs, and adding a manual factorization to compare with.  I also reworked the tensor intermediate definition within CTF, so it should work for cases like this better (with v1.34 it should not compute any intermediate of order higher than 6 for that expression).  However, the factorization approach used still has no quality guarantees for factorizations in general (if you reorder the tensors in the contraction chain in your code, CTF may again get confused and compute intermediates of high order).  Compile CTF with -DVERBOSE to see what contractions it actually computes.  There are plans to improve CTF factorization functionality further in the future.

**Comment by kostrzewa** [comment]
Hi, my apologies for taking so long to get back to you. Thanks a lot for fixing my test case!

This test was very interesting for us because the complexity of our contractions is steadily increasing. I will have to study a bit more how to sensibly fill the tensor objects with data, but the time per contraction is quite impressive, given the generality of ctf.

The way I wrote the contraction was a bit of an extreme case to see just how long this kind of thing would take. In practice, we would also order the contraction by hand, as you did for my test case.

We will try this out with actual examples over the coming months and I'll try to keep you informed. If we find that ctf is just what we need and continue to use, do we cite the three papers mentioned on the website or is there a specific one which you would like to see cited in this context?

**Comment by solomonik** [comment]
Just citing the JPDC paper is appreciated, feel free to post more questions/feedback.
