### ISSUE TITLE
parallel random number generation

### ISSUE THREAD

**Issue by jeffhammond** [solomonik/ctf#30]
(continuing discussion from https://github.com/solomonik/ctf/issues/27#issuecomment-251461600 in a better place)

> (Sorry for the off-topic discussion.) CTF currently requires C++11. I am happy to learn C++11 has more robust support for RNGs and will keep that in mind. However, I am not sure they provide a solution to the underlying problem with parallel RNG generation for a library like CTF. One can just generate non-deterministically, but determinism is extremely valuable for reproducible testing. However, then one has to insure that different processors get a different seed and different tensors get a different seed, and it becomes not so clear how to do that (e.g. on a CTF instance basis or via global counter) and how to let the user control it.
> 
> I guess the right solution might be to have fill_random_nondeterministic and fill_random_preseeded. Then it remains to figure out whether fill_random_preseeded should have all processor ranks with the same seed or with a different seed, and how to handle the former, which is where C++11 RNGs may help. And what fill_random should do for backwards comp.

I recall @poulson worked on this w.r.t. [Elemental](https://github.com/elemental/Elemental) a while back but I cannot find the emails about it.  However, it had something to do with Random123 (see [this](https://github.com/DEShawResearch/Random123-Boost) and [this](http://www.thesalmons.org/john/random123/) for details).  I can't tell if this is implemented in https://github.com/elemental/Elemental/tree/master/include/El/core/random though.

**Comment by poulson** [comment]
I used to evenly split the stream of numbers produced by a Linear Congruential Generator by recognizing that f (x) = (a x + b) mod n composed with itself p times is again an LCG and one can easily compute the coefficients (as well as the appropriate seeds for each of the p processes). 

But LCG's are rudimentary RNG's, so I instead switched to giving each worker a unique seed for C++11's Mersenne twister.

**Comment by solomonik** [comment]
@jeffhammond thanks for creating a separate issue.  I am well aware of Random123 and tried working with it a few years back, but found the interface rather confusing.  Looks like C++11 now has the main algorithms that Random123 does, perhaps this is even something DESRES pushed through into C++.

@poulson this sounds like a good solution, but do you reconstruct the mersenne twister engine every time an instance of Elemental (of the Environment I guess) is created, or keep it around as a global variable?  I guess I would potentially be paranoid about someone writing a randomized algorithm that creates a new instance of the library in the inner loop, losing randomness, but that could be disregarded as inappropriate usage.  Or on the other hand, a test driver that calls a test which creates a new instance, but gets different results dependent on whether tests with other instances were done previously.

**Comment by poulson** [comment]
I only allow one internal instance of Environment, but I reference count it and internally destruct when all external instances have been destructed.

**Comment by solomonik** [comment]
Ok thanks, CTF also has a counter for the number of existing `worlds'.  I was worried about the case when all worlds/instances get destroyed and a new one gets created.  But I guess reseeding is less dangerous than relying on some persistent global variable.  Think I will implement the same approach.
