### ISSUE TITLE
Set::abs not set in some instances

### ISSUE THREAD

**Issue by devinamatthews** [solomonik/ctf#8]
In some instances (in particular, when calling `Tensor::reduce(OP_MAXABS)`), the `abs` field of `Monoid mmax` (src/tensor.cxx:650) is NULL, which leads to a segfault in `seq_tsr_sum::run`. It seems that this is initially set to NULL in the default `Set` constructor, and not later initialized with `Set::set_abs_to_default()`? This function does not seem to be ever referenced. Should this be done in `Set::Set()`?

**Comment by devinamatthews** [comment]
I should note that this is working from the v1.32 tag, and that this did not happen on v1.31.

**Comment by solomonik** [comment]
Hi Devin.  Thanks for the bug report.  You are completely correct.  I fixed this and updated the release tag to point to the new commit.  Please let me know if you see any other issues.  Sorry, forgot to test this version with AQ.
